name: CI (build on macOS + Linux)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Show brew info
        run: |
          brew --version
          brew config
          brew doctor || true

      - name: Pre-clean
        run: brew test-bot --only-cleanup-before

      - name: Setup test-bot
        run: brew test-bot --only-setup

      - name: Tap syntax check
        run: brew test-bot --only-tap-syntax

      - name: Build formulae
        run: brew test-bot --only-formulae
